version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: citas_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: CitasService
      MYSQL_USER: User1
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
     - ./db_data:/var/lib/mysql

